//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public System.Guid FilmId { get; set; }
        public Rentals.Enums.Genres Genre { get; set; }
        public string Series { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public string Details { get; set; }
        public Nullable<int> NumberofSeries { get; set; }
        public bool Available { get; set; }
    }
}
